### Home
GET http://localhost:3000

### Obtener todas todas las tareas
GET http://localhost:3000/api/tasks

### Obtener una tarea por id
GET http://localhost:3000/api/tasks/1

### Crear una nueva tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Configurar CI/CD pipeline",
  "description": "Automatizar despliegues con GitHub Actions para testing y producción",
  "completed": true
}

### Actualizar una tarea existente
PATCH  http://localhost:3000/api/tasks/2
Content-Type: application/json

{
  "title" : "Actualizado desde patch.",
  "completed": true
}

### Eliminar una tarea
DELETE http://localhost:3000/api/tasks/3

### Manejando 404
GET http://localhost:3000/asdasd